=== aws-solutions/unified-profile-for-travellers-and-guests-on-aws/source/test_data/schemas/lodging/hotel_stay_revenue.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$ref": "#/$defs/Stay",
  "$defs": {
    "AlternateProfileID": {
      "properties": {
        "name": {
          "type": "string"
        },
        "value": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "lastUpdatedOn": {
          "type": "string",
          "format": "date-time"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name",
        "value",
        "lastUpdatedOn"
      ]
    },
    "Currency": {
      "properties": {
        "code": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "symbol": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "code"
      ]
    },
    "Stay": {
      "properties": {
        "objectVersion": {
          "type": "integer"
        },
        "modelVersion": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "bookingId": {
          "type": "string"
        },
        "guestId": {
          "type": "string"
        },
        "lastUpdatedOn": {
          "type": "string",
          "format": "date-time"
        },
        "createdOn": {
          "type": "string",
          "format": "date-time"
        },
        "lastUpdatedBy": {
          "type": "string"
        },
        "createdBy": {
          "type": "string"
        },
        "currency": {
          "$ref": "#/$defs/Currency"
        },
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "startDate": {
          "type": "string"
        },
        "hotelCode": {
          "type": "string"
        },
        "revenue": {
          "items": {
            "$ref": "#/$defs/StayRevenueItem"
          },
          "type": "array"
        },
        "alternateProfileIds": {
          "items": {
            "$ref": "#/$defs/AlternateProfileID"
          },
          "type": "array"
        },
        "extendedData": true
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "objectVersion",
        "modelVersion",
        "id",
        "bookingId",
        "guestId",
        "lastUpdatedOn",
        "createdOn",
        "lastUpdatedBy",
        "createdBy",
        "currency",
        "firstName",
        "lastName",
        "email",
        "phone",
        "startDate",
        "hotelCode",
        "revenue"
      ]
    },
    "StayRevenueItem": {
      "properties": {
        "type": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "currency": {
          "$ref": "#/$defs/Currency"
        },
        "amount": {
          "type": "number"
        },
        "date": {
          "type": "string",
          "format": "date-time"
        },
        "extendedData": true
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "type",
        "description",
        "currency",
        "amount",
        "date"
      ]
    }
  }
}

=== aws-solutions/unified-profile-for-travellers-and-guests-on-aws/source/test_data/hotel_stay/data2.json
{"objectVersion":8,"modelVersion":"1.0","id":"AEAWOEPI33","bookingId":"NQX5BPMBT0","guestId":"8648033592","lastUpdatedOn":"2023-05-21T06:54:17.005561333Z","createdOn":"2023-04-28T12:01:35.182390622Z","lastUpdatedBy":"Avis White","createdBy":"Cristobal Hessel","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"firstName":"Nina","lastName":"Koepp","email":"shannyharber@glover.name","phone":"93821.350.2933","startDate":"2023-04-14","hotelCode":"LON04","revenue":[{"type":"Room Charge 2023-05-27","description":"King Room with Sea View ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":1356.5239,"date":"2023-05-27T00:00:00Z"},{"type":"Room Charge 2023-05-27","description":"Doubel room with Sea View ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":431.14362,"date":"2023-05-27T00:00:00Z"},{"type":"Room Charge 2023-05-27","description":"Suite with  ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":2180.0903,"date":"2023-05-27T00:00:00Z"},{"type":"Room Charge 2023-05-28","description":"King Room with Sea View ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":1424.4155,"date":"2023-05-28T00:00:00Z"},{"type":"Room Charge 2023-05-28","description":"Doubel room with Sea View ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":800.9849,"date":"2023-05-28T00:00:00Z"},{"type":"Room Charge 2023-05-28","description":"Suite with  ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":2112.3096,"date":"2023-05-28T00:00:00Z"},{"type":"Room Charge 2023-05-29","description":"King Room with Sea View ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":1228.9974,"date":"2023-05-29T00:00:00Z"},{"type":"Room Charge 2023-05-29","description":"Doubel room with Sea View ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":578.6895,"date":"2023-05-29T00:00:00Z"},{"type":"Room Charge 2023-05-29","description":"Suite with  ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":1960.501,"date":"2023-05-29T00:00:00Z"},{"type":"Room Charge 2023-05-30","description":"King Room with Sea View ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":1768.3807,"date":"2023-05-30T00:00:00Z"},{"type":"Room Charge 2023-05-30","description":"Doubel room with Sea View ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":368.98334,"date":"2023-05-30T00:00:00Z"},{"type":"Room Charge 2023-05-30","description":"Suite with  ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":1566.4902,"date":"2023-05-30T00:00:00Z"},{"type":"Room Charge 2023-05-31","description":"King Room with Sea View ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":737.51746,"date":"2023-05-31T00:00:00Z"},{"type":"Room Charge 2023-05-31","description":"Doubel room with Sea View ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":693.15405,"date":"2023-05-31T00:00:00Z"},{"type":"Room Charge 2023-05-31","description":"Suite with  ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":2059.9062,"date":"2023-05-31T00:00:00Z"},{"type":"Room Charge 2023-06-01","description":"King Room with Sea View ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":1572.8229,"date":"2023-06-01T00:00:00Z"},{"type":"Room Charge 2023-06-01","description":"Doubel room with Sea View ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":305.53955,"date":"2023-06-01T00:00:00Z"},{"type":"Room Charge 2023-06-01","description":"Suite with  ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":1572.4144,"date":"2023-06-01T00:00:00Z"},{"type":"Room Charge 2023-06-02","description":"King Room with Sea View ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":1668.9247,"date":"2023-06-02T00:00:00Z"},{"type":"Room Charge 2023-06-02","description":"Doubel room with Sea View ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":866.98724,"date":"2023-06-02T00:00:00Z"},{"type":"Room Charge 2023-06-02","description":"Suite with  ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":1091.6896,"date":"2023-06-02T00:00:00Z"},{"type":"Room Charge 2023-06-03","description":"King Room with Sea View ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":687.0226,"date":"2023-06-03T00:00:00Z"},{"type":"Room Charge 2023-06-03","description":"Doubel room with Sea View ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":811.958,"date":"2023-06-03T00:00:00Z"},{"type":"Room Charge 2023-06-03","description":"Suite with  ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":2123.0632,"date":"2023-06-03T00:00:00Z"},{"type":"Room Charge 2023-06-04","description":"King Room with Sea View ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":663.52,"date":"2023-06-04T00:00:00Z"},{"type":"Room Charge 2023-06-04","description":"Doubel room with Sea View ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":325.3348,"date":"2023-06-04T00:00:00Z"},{"type":"Room Charge 2023-06-04","description":"Suite with  ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":1592.731,"date":"2023-06-04T00:00:00Z"},{"type":"snack bar","description":"","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":88.70536,"date":"2023-05-09T22:01:37.257863273Z"},{"type":"snack bar","description":"","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":42.5373,"date":"2023-05-14T03:28:10.179138064Z"},{"type":"Room Charge 2023-05-27","description":"King Room with Sea View,Mini bar ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":2235.3765,"date":"2023-05-27T00:00:00Z"},{"type":"Room Charge 2023-05-27","description":"Suite with  ( Xmas special rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":1662.1243,"date":"2023-05-27T00:00:00Z"},{"type":"Room Charge 2023-05-27","description":"Suite with Balcony ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":1235.751,"date":"2023-05-27T00:00:00Z"},{"type":"Room Charge 2023-05-27","description":"Doubel room with  ( Super Saver rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":537.6124,"date":"2023-05-27T00:00:00Z"},{"type":"Room Charge 2023-05-28","description":"King Room with Sea View,Mini bar ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":2739.0742,"date":"2023-05-28T00:00:00Z"},{"type":"Room Charge 2023-05-28","description":"Suite with  ( Xmas special rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":1143.3607,"date":"2023-05-28T00:00:00Z"},{"type":"Room Charge 2023-05-28","description":"Suite with Balcony ( Best avaialble rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":816.6425,"date":"2023-05-28T00:00:00Z"},{"type":"Room Charge 2023-05-28","description":"Doubel room with  ( Super Saver rate)","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":376.7884,"date":"2023-05-28T00:00:00Z"},{"type":"snack bar","description":"","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":70.10985,"date":"2023-04-20T06:35:49.686652582Z"},{"type":"snack bar","description":"","currency":{"code":"TJS","name":"Tajikistan Somoni","symbol":""},"amount":55.585194,"date":"2023-05-23T20:50:24.270282785Z"}]}
